Check for the old licenses.

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -46,7 +46,6 @@ fi
 # be strict about tabs - we don't want them at all, setup your editor
 # correctly ;-)
 CHECK_EXTENSIONS='\.\(c\|cpp\|cxx\|h\|hrc\|hxx\|idl\|inl\|java\|map\|mk\|MK\|pmk\|pl\|pm\|sdi\|sh\|src\|tab\|xcu\|xml\)$'
-
 ERRORS="$(git diff-index --cached --name-only HEAD | while read FILE ; do
               if echo "$FILE" | grep -qs "$CHECK_EXTENSIONS" ; then
                   if git diff-index -p --cached HEAD -- "$FILE" | grep -qs $'^+ *\t' ; then
@@ -61,6 +60,24 @@ if test -n "$ERRORS" ; then
     echo
     echo "Please setup your editor not to use tabs, fix the files, and try again."
     echo "We have had enough trouble with tabs in the past :-("
+    echo
+    exit 1
+fi
+
+# check for old licenses
+CHECK_LICENSES='^+.*\(Sun Industry Standards Source License Version\|GNU Lesser General Public License Version 2.1\)'
+ERRORS="$(git diff-index --cached --name-only HEAD | while read FILE ; do
+              if git diff-index -p --cached HEAD -- "$FILE" | grep -qs "$CHECK_LICENSES" ; then
+                  echo "$FILE"
+              fi
+          done)"
+if test -n "$ERRORS" ; then
+    echo "Error: Your change in the following files introduces old licenses:"
+    echo
+    echo "$ERRORS"
+    echo
+    echo "Please check with the author(s) that they agree with upgrading the"
+    echo "license to LGPL3, and change the license accondingly."
     echo
     exit 1
 fi
