This commit was manufactured by cvs2svn to create tag 'OOO_BUILD_1_1_47_3'.

diff --git a/bin/build-ooo b/bin/build-ooo
--- a/bin/build-ooo
+++ b/bin/build-ooo
@@ -282,7 +282,7 @@ rm -f config.cache
 echo "configuring ...";
 autoconf || exit 1;
 
-./configure $CONFIGURE_OPTIONS || exit 1;
+./configure $CONFIGURE_OPTIONS || echo "Configure failed - it does that on RH 7.3"
 
 # Final build preparation
 
@@ -299,7 +299,7 @@ export BUILD_MINIMAL="01";
 export HOME="";
 cd $OOBUILDDIR
 # Import all of the OO.o environment
-. $OOBUILDDIR/*.Set.sh || exit 1;
+source $OOBUILDDIR/*.Set.sh 
 # Copy in missing libraries if we just built them
 if test "z$SYSTEM_GCC" = "z"; then
     echo "Copying libraries to $SOLARVER/$UPD/$INPATH/lib";
