Added plain branch checkout support to g
* bin/g: made 'bin/g checkout <branch>' work

diff --git a/bin/g b/bin/g
--- a/bin/g
+++ b/bin/g
@@ -73,10 +73,15 @@ while shift ; do
         fi
         FILES[$FILESNUM]=`readlink -n -e "$PARAM"`
         if [ -z "${FILES[$FILESNUM]}" ] ; then
-            echo "'$PARAM' not found in `pwd`."
-            exit 1
+            if [ "$COMMAND" = "checkout" ] ; then
+                EXTRA="$EXTRA $PARAM"
+            else
+                echo "'$PARAM' not found in `pwd`."
+                exit 1
+            fi
+        else
+            FILESNUM=$(($FILESNUM+1))
         fi
-        FILESNUM=$(($FILESNUM+1))
     fi
 done
 
@@ -140,7 +145,7 @@ for DIR in * ; do
             # check for changes
             HEADREF=`git show-ref --head HEAD`
 
-            git $PAGER "$COMMAND" $EXTRA "${FILES[@]}"
+            git $PAGER $COMMAND $EXTRA ${FILES[@]}
             RETURN=$?
 
             # update stamp if the repo changed
