Check for tabs in patches when doing 'g apply'.

diff --git a/bin/g b/bin/g
--- a/bin/g
+++ b/bin/g
@@ -35,6 +35,15 @@ while shift ; do
         FILES[$FILESNUM]="$1"
         FILESNUM=$(($FILESNUM+1))
     else
+        if [ "$COMMAND" = "apply" ] ; then
+            grep -qs $'^+ *\t' "$1" && {
+                echo "Patch '$1' introduces tabs in indentation, aborting."
+                echo
+                echo "Please fix the patch (something like s/^\(+ *\)\t/\1    /) and try again."
+                echo
+                exit 1
+            }
+        fi
         FILES[$FILESNUM]=`readlink -n -f "$1"`
         FILESNUM=$(($FILESNUM+1))
     fi
@@ -44,11 +53,11 @@ CLONEDIR=`readlink -e $0 | sed 's#/bin/g$#/clone#'`
 cd "$CLONEDIR"
 
 # do it!
-for dir in * ; do
-    if [ -d "$dir" -a -d "$dir"/.git ] ; then
+for DIR in * ; do
+    if [ -d "$DIR" -a -d "$DIR"/.git ] ; then
         (
-            echo "===== $dir ====="
-            cd $dir
+            echo "===== $DIR ====="
+            cd $DIR
             case "$COMMAND" in
                 apply)
                     for I in * ; do
@@ -67,5 +76,12 @@ for dir in * ; do
         ) || exit $?
     fi
 done
+
+# warn
+if [ "$COMMAND" = "apply" ] ; then
+    echo
+    echo "Don't forget to check the status & commit now ;-)"
+    echo
+fi
 
 # vi:set expandtab:
