Check for existence of vcredist\*.exe and copy into the tree
Break early if they are not there

diff --git a/bin/unpack b/bin/unpack
--- a/bin/unpack
+++ b/bin/unpack
@@ -208,6 +208,30 @@ if test "z$BUILD_WIN32" != "z"; then
 	echo "and can't easily be automated."
 	exit 1
     fi
+
+    $echo_n "Looking for $SRCDIR/vcredist_x86.exe ... $echo_c"
+    if test -f $SRCDIR/vcredist_x86.exe; then
+	echo "ok"
+    else
+	echo "missing"
+	echo "Get it from the Microsoft site and put it into $SRCDIR."
+	echo "You may have to search Microsoft's website."
+	echo "Look for the version of 32-bit runtime redistribuable that corresponds"
+	echo "to the version your Visual Studio links with"
+	exit 1
+    fi
+
+    $echo_n "Looking for $SRCDIR/vcredist_x64.exe ... $echo_c"
+    if test -f $SRCDIR/vcredist_x64.exe; then
+	echo "ok"
+    else
+	echo "missing"
+	echo "Get it from the Microsoft site and put it into $SRCDIR."
+	echo "You may have to search Microsoft's website."
+	echo "Look for the version of 64-bit runtime redistribuable that corresponds"
+	echo "to the version your Visual Studio links with"
+	exit 1
+    fi
 fi
 
     case "$DISTRO" in
