Do include msvcr71.dll, and some MSI build tweaks
Restore code into bin/unpack to look for msvcr71.dll and copyt it into
external/msvcp71. Always included it on Windows in
common_brand.scp. Java needs it.

When building the installer and reloading .idt files after editing
them, for instance MsiAssem.idt (see mergemodule.pm), run msidb on
just one table at a time. Also, save old files by prefixing with
"old." in addition to suffixing with ".1", ".2" etc. Either one or
both of these changes made including the merge assemblies for the VC9
runtime actually work for me. Why it didn't work for me but works fine
on the "bill" build machine I don't know. Might be because I have
turned off 8.3 name generation on the volume where I build OOo.

M	bin/unpack
M	patches/dev300/build-fix-win32.diff

diff --git a/bin/unpack b/bin/unpack
--- a/bin/unpack
+++ b/bin/unpack
@@ -154,6 +154,22 @@ if test "z$BUILD_WIN32" != "z"; then
 	fi
     done
 
+     # msvcr71.dll that JRE needs
+     for F in msvcr71.dll; do
+ 	$echo_n "Looking for $SRCDIR/$F ...  $echo_c"
+ 	if test -f $SRCDIR/$F; then
+ 	    echo "ok"
+ 	elif test -f "$WINDIR/system32/$F"; then
+ 	    echo "missing, but copied from $WINDIR/system32"
+ 	    cp "$WINDIR/system32/$F" $SRCDIR
+ 	else
+ 	    echo "missing"
+ 	    echo "You can find it in MSVS .NET 2003."
+ 	    echo "It is needed by JRE"
+ 	    exit 1
+ 	fi
+     done
+ 
     # instmsi?.exe are the installers for Windows Installer 2.0 for
     # Win9x, Windows NT 4 and Windows 2000, that nobody really needs
     # (I hope). But the installer-builder insists on including them
@@ -527,6 +543,12 @@ if test "z$BUILD_WIN32" != "z"; then
 	CommonProgsX86="$COMMONPROGRAMFILES"
     fi
 
+     if test -f $OOBUILDDIR/external/msvcp71/msvcr71.dll; then
+ 	echo "Already have msvcr71.dll"
+     else
+ 	$GNUCP -p $SRCDIR/msvcr71.dll $OOBUILDDIR/external/msvcp71
+     fi
+ 
     if test -f $OOBUILDDIR/external/msm90/Microsoft_VC90_CRT_x86.msm -a \
             -f $OOBUILDDIR/external/msm90/policy_9_0_Microsoft_VC90_CRT_x86.msm; then
 	echo "Already have Microsoft_VC90_CRT_x86.msm and policy_9_0_Microsoft_VC90_CRT_x86.msm"
