First attempt to handle VC80 CRT used by prebuilt Mozilla bits

diff --git a/bin/unpack b/bin/unpack
--- a/bin/unpack
+++ b/bin/unpack
@@ -131,6 +131,20 @@ if test "z$BUILD_WIN32" != "z"; then
     check_file $SRCDIR/WNTMSCIlib.zip
     check_file $SRCDIR/WNTMSCIruntime.zip
 
+    # CRT80 that the prebuilt Mozilla needs and the
+    # installer-builder wants to put in the installer
+    for F in msvcr80.dll msvcp80.dll Microsoft.VC80.CRT.manifest; do
+	$echo_n "Looking for $SRCDIR/$F ...  $echo_c"
+	if test -f $SRCDIR/$F; then
+	    echo "ok"
+	else
+	    echo "missing"
+	    echo "You can find it in MSVS 2008, in VC/redist/x86/Microsoft.VC80.CRT."
+	    echo "It is needed by the prebuilt Mozilla binaries that you should use."
+	    exit 1
+	fi
+    done
+
     # instmsi?.exe are the installers for Windows Installer 2.0 for
     # Win9x, Windows NT 4 and Windows 2000, that nobody really needs
     # (I hope). But the installer-builder insists on including them
