This commit was manufactured by cvs2svn to create tag 'OOO_BUILD_2_0_4_11'.

diff --git a/bin/unpack b/bin/unpack
--- a/bin/unpack
+++ b/bin/unpack
@@ -52,6 +52,18 @@ if test "z$BUILD_WIN32" != "z"; then
     check_file $SRCDIR/libIDL-0.6.8.tar.gz
     check_file $SRCDIR/libIDL-0.6.8-ooo.patch
     check_file $SRCDIR/wintools.zip
+    echo -n "Looking for $SRCDIR/gdiplus.dll ... "
+    if test ! -f $SRCDIR/gdiplus.dll; then
+	echo "missing"
+	echo "Get it from the Microsoft site and put it into $SRCDIR"
+	echo "You may have to search Microsoft's website."
+	echo "Last time it was seen at: http://www.microsoft.com/downloads/details.aspx?familyid=6A63AB9C-DF12-4D41-933C-BE590FEAA05A&displaylang=en"
+	echo "Note that the download requires Genuine Windows validation"
+	echo "and can't easily be automated."
+	exit 1
+    else
+	echo "ok"
+    fi
 fi
 
 if test "z$SYSTEM_GCC" = "z"; then
@@ -141,8 +153,8 @@ fi
 if test "z$BUILD_WIN32" != "z"; then
 # FIXME: add check for system bits ...
 
-    # ODMA
-	echo "ODMA disabled for now."
+    # ODMA SDK
+	echo "ODMA SDK disabled for now."
 #    cd $BUILDDIR;
 #    DEST=$OOBUILDDIR/ucb/source/ucp/odma
 #    if test ! -f $DEST/ODMA.H; then
@@ -160,6 +172,12 @@ if test "z$BUILD_WIN32" != "z"; then
 #    else
 #	echo "Already have ODMA SDK";
 #    fi
+
+    # gdiplus.dll
+    cd $BUILDDIR;
+    if test ! -f $OOBUILDDIR/external/gdiplus/gdiplus.dll; then
+	cp -p $SRCDIR/gdiplus.dll $OOBUILDDIR/external/gdiplus/gdiplus.dll
+    fi
 
     # dbghelp
     cd $BUILDDIR;
@@ -274,6 +292,79 @@ if test "z$BUILD_WIN32" != "z"; then
             echo "Already have DejaVu fonts"
         fi
     fi
+
+    # Mono runtime dependency: GLib and its depencencies (mono itself
+    # is statically linked in our build of OdfConverter).
+    # For now put in own subfolder under "external", but there is no
+    # mechanisms yet in place to deliver them from there to solver's bin
+    # folder where the installer-builder will look for them. So maybe
+    # just could be lazy and rude and put them straight into solver's bin?
+    cd $BUILDDIR
+    if test ! -f $OOBUILDDIR/external/glib/libglib-2.0-0.dll; then
+	echo -n "Extracting libglib-2.0-0.dll "
+	unzip $SRCDIR/glib-2.12.4.zip bin/libglib-2.0-0.dll
+	mkdir -p $OOBUILDDIR/external/glib
+	mv bin/libglib-2.0-0.dll $OOBUILDDIR/external/glib
+	echo "done"
+    fi
+    if test ! -f $OOBUILDDIR/external/glib/libgmodule-2.0-0.dll; then
+	echo -n "Extracting libgmodule-2.0-0.dll "
+	unzip $SRCDIR/glib-2.12.4.zip bin/libgmodule-2.0-0.dll
+	mkdir -p $OOBUILDDIR/external/glib
+	mv bin/libgmodule-2.0-0.dll $OOBUILDDIR/external/glib
+	echo "done"
+    fi
+    if test ! -f $OOBUILDDIR/external/glib/libgthread-2.0-0.dll; then
+	echo -n "Extracting libgthread-2.0-0.dll "
+	unzip $SRCDIR/glib-2.12.4.zip bin/libgthread-2.0-0.dll
+	mkdir -p $OOBUILDDIR/external/glib
+	mv bin/libgthread-2.0-0.dll $OOBUILDDIR/external/glib
+	echo "done"
+    fi
+    if test ! -f $OOBUILDDIR/external/glib/intl.dll; then
+	echo -n "Extracting intl.dll "
+	unzip $SRCDIR/gettext-0.14.5.zip bin/intl.dll
+	mkdir -p $OOBUILDDIR/external/glib
+	mv bin/intl.dll $OOBUILDDIR/external/glib
+	echo "done"
+    fi
+    if test ! -f $OOBUILDDIR/external/glib/iconv.dll; then
+	echo -n "Extracting iconv.dll "
+	unzip $SRCDIR/libiconv-1.9.1.bin.woe32.zip bin/iconv.dll
+	mkdir -p $OOBUILDDIR/external/glib
+	mv bin/iconv.dll $OOBUILDDIR/external/glib
+	echo "done"
+    fi
+    # odfconverter.exe
+    if test ! -f $OOBUILDDIR/external/odfconverter/odfconverter.exe; then
+	echo -n "Extracting odfconverter.exe "
+	unzip $SRCDIR/odfconverter-0.0.5-win32.zip odfconverter.exe
+	mkdir -p $OOBUILDDIR/external/odfconverter
+	mv odfconverter.exe $OOBUILDDIR/external/odfconverter
+	echo "done"
+    fi
+    # zlib1.dll, used by OdfConverter
+    if test ! -f $OOBUILDDIR/external/zlib1dll/zlib1.dll; then
+	echo -n "Extracting zlib1.dll "
+	unzip $SRCDIR/zlib123-dll.zip zlib1.dll
+	mkdir -p $OOBUILDDIR/external/zlib1dll
+	mv zlib1.dll $OOBUILDDIR/external/zlib1dll
+	echo "done"
+    fi
+
+    # Icons.
+    # Just plunk them on top of the upstream ones for now. I'm
+    # too lazy to add configury to make it optional and to check for
+    # existence of the tarball, etc.
+    case "$DISTRO" in
+	# Add other Win32 "distros" here if they too want to use
+	# these icons
+        NovellWin32*)
+	    tar xfj $SRCDIR/ooo-windows-icons-0.1.tar.bz2
+	    rm ico/ooo-web-app.ico
+	    mv ico/ooo-*.ico $OOBUILDDIR/sysui/desktop/icons
+	    ;;
+    esac
 fi
 
 if test "z$SYSTEM_GCC" = "z"; then
@@ -294,6 +385,19 @@ if test "x$OOO_EXTRA_ARTWORK" != "x"; then
     cd $OOBUILDDIR
     tar xjf $SRCDIR/$OOO_EXTRA_ARTWORK || exit 1;
 fi
+
+for i in $OOO_LANGS; do
+	if [ -e $SRCDIR/extras_${i}.tar.gz ]; then
+		echo "Extracting extra ${i} extras"
+		cd $OOBUILDDIR
+		tar xzf $SRCDIR/extras_${i}.tar.gz || exit 1
+	fi
+	if [ -e $SRCDIR/help_images_${i}.tar.gz ]; then
+		echo "Extracting extra ${i} help images"
+		cd $OOBUILDDIR
+		tar xzf $SRCDIR/help_images_${i}.tar.gz || exit 1
+	fi
+done
 
 if test "x$OPENCLIPART_VER" != "x"; then
     echo "Unpacking open clipart"
@@ -364,11 +468,4 @@ check_tarball $SRCDIR/$LPSOLVE_PACKAGE
 echo "Copying lp_solve package into the tree"
 mkdir -p $OOBUILDDIR/lpsolve/download || exit 1
 cp -a $SRCDIR/$LPSOLVE_PACKAGE $OOBUILDDIR/lpsolve/download/ || exit 1
-
-# add license-fixed rhino
-if test "$VENDORNAME" = "Debian"; then
-	if echo $CVSTAG | grep -q ood680 && test "`echo $CVSTAG | cut -d'-' -f2`" = "m1"; then
-		cp $SRCDIR/rhino1_5R4.patch $OOBUILDDIR/rhino || exit 1
-	fi
-fi
 
