This commit was manufactured by cvs2svn to create tag 'OOO_BUILD_2_0_4_6'.

diff --git a/bin/unpack b/bin/unpack
--- a/bin/unpack
+++ b/bin/unpack
@@ -52,6 +52,18 @@ if test "z$BUILD_WIN32" != "z"; then
     check_file $SRCDIR/libIDL-0.6.8.tar.gz
     check_file $SRCDIR/libIDL-0.6.8-ooo.patch
     check_file $SRCDIR/wintools.zip
+    echo -n "Looking for $SRCDIR/gdiplus.dll ... "
+    if test ! -f $SRCDIR/gdiplus.dll; then
+	echo "missing"
+	echo "Get it from the Microsoft site and put it into $SRCDIR"
+	echo "You may have to search Microsoft's website."
+	echo "Last time it was seen at: http://www.microsoft.com/downloads/details.aspx?familyid=6A63AB9C-DF12-4D41-933C-BE590FEAA05A&displaylang=en"
+	echo "Note that the download requires Genuine Windows validation"
+	echo "and can't easily be automated."
+	exit 1
+    else
+	echo "ok"
+    fi
 fi
 
 if test "z$SYSTEM_GCC" = "z"; then
@@ -160,6 +172,12 @@ if test "z$BUILD_WIN32" != "z"; then
 #    else
 #	echo "Already have ODMA SDK";
 #    fi
+
+    # gdiplus.dll
+    cd $BUILDDIR;
+    if test ! -f $OOBUILDDIR/external/gdiplus/gdiplus.dll; then
+	cp -p $SRCDIR/gdiplus.dll $OOBUILDDIR/external/gdiplus/gdiplus.dll
+    fi
 
     # dbghelp
     cd $BUILDDIR;
@@ -295,6 +313,19 @@ if test "x$OOO_EXTRA_ARTWORK" != "x"; then
     tar xjf $SRCDIR/$OOO_EXTRA_ARTWORK || exit 1;
 fi
 
+for i in $OOO_LANGS; do
+	if [ -e $SRCDIR/extras_${i}.tar.gz ]; then
+		echo "Extracting extra ${i} extras"
+		cd $OOBUILDDIR
+		tar xzf $SRCDIR/extras_${i}.tar.gz || exit 1
+	fi
+	if [ -e $SRCDIR/help_images_${i}.tar.gz ]; then
+		echo "Extracting extra ${i} help images"
+		cd $OOBUILDDIR
+		tar xzf $SRCDIR/help_images_${i}.tar.gz || exit 1
+	fi
+done
+
 if test "x$OPENCLIPART_VER" != "x"; then
     echo "Unpacking open clipart"
     check_tarball $SRCDIR/openclipart-$OPENCLIPART_VER.tar.bz2
@@ -364,11 +395,4 @@ check_tarball $SRCDIR/$LPSOLVE_PACKAGE
 echo "Copying lp_solve package into the tree"
 mkdir -p $OOBUILDDIR/lpsolve/download || exit 1
 cp -a $SRCDIR/$LPSOLVE_PACKAGE $OOBUILDDIR/lpsolve/download/ || exit 1
-
-# add license-fixed rhino
-if test "$VENDORNAME" = "Debian"; then
-	if echo $CVSTAG | grep -q ood680 && test "`echo $CVSTAG | cut -d'-' -f2`" = "m1"; then
-		cp $SRCDIR/rhino1_5R4.patch $OOBUILDDIR/rhino || exit 1
-	fi
-fi
 
