Update the branding installation for ooo320-m14 for the split build
* bin/piece/file-list-postprocess: install also intro.png; install about.png
  instead of about.bmp
* bin/piece/install-bootstrap: install the built sofficerc
* bin/piece/post-inst-postprocess: check and remove the installed sofficerc
  if the prebuilt was used
* bin/setup.in: export OOO_BUILD_NOARCH
* src/Makefile.am: pack sofficerc-upstream
* src/sofficerc-upstream: we need the prebuilt config file to allow separate
  branding package and to avoid devel package in the post process

diff --git a/bin/piece/post-inst-postprocess b/bin/piece/post-inst-postprocess
--- a/bin/piece/post-inst-postprocess
+++ b/bin/piece/post-inst-postprocess
@@ -24,6 +24,20 @@ UNO_JAVA_JFW_VENDOR_SETTINGS=file://$OO_INSTDIR/ure/share/misc/javavendors.xml
 EOT
 export JVMFWK_CONFIGFILE=file://`pwd`/jvmfwk3rc
 
+# check and remove the sofficerc
+# we use the prebuilt one in the upstream branding package
+# FIXME: it would be possible to generate this file by the installer, e.g. in bootstrap
+if test "$DISTRO" = "SUSE" || echo "$DISTRO" | grep -q "SUSE-11" ; then
+    if diff -q $DESTDIR$OO_INSTDIR/program/sofficerc $OO_INSTDIR_SHARE/ooo-build/src/sofficerc-upstream ; then
+	rm $DESTDIR$OO_INSTDIR/program/sofficerc
+	ln -sf $OO_INSTDIR_SHARE/program/sofficerc $DESTDIR$OO_INSTDIR/program/sofficerc
+    else
+	echo "Error: The file \"sofficerc\" has changed in the sources"
+	echo "       Please, update the prebuilt variant in $OO_INSTDIR_SHARE/ooo-build/src/sofficerc-upstream"
+	exit 1;
+    fi
+fi
+
 # needed to register python components
 export PYTHONPATH=$OO_INSTDIR/basis$VERSION/program
 
